mainConfig:
  type: esbuild
  path: esbuild.main.config.ts
  src: src/gui/main/main.ts
  output:
    dir: dist/main
    filename: main.js
rendererConfig:
  type: esbuild
  path: esbuild.renderer.config.ts
  html: src/gui/renderer/index.html
  src: src/gui/renderer/index.tsx
  output:
    dir: dist/renderer
    filename: index.js